# Find and clean faults in transactions.csv

In [1]:
import pandas as pd

file = "data/transactions_original.csv"

df_transactions = pd.read_csv(file)
# display(df_transactions.head())
# print(df_transactions.dtypes)

# print(df_transactions.columns)
# this filename is f26185400.ipynb from dataretrieval

/tmp/ipykernel_10655/2923823477.py:5: DtypeWarning: Columns (2) have mixed types. Specify dtype option on import or set low_memory=False.
  df_transactions = pd.read_csv(file)

## First check
Compatibility against database-constraints
only nullable and datatype.
Discarded rows to df_errors, approved to df_parsed.
df_errors contains one extra row: ["error_messages]

In [2]:
# df_parsed = pd.DataFrame()

def check_transaction_id(cell):
    """I would want this to be a class instead. ParentClass: stdsearches. Others inherit with specific attributes and settings"""
    error_messages = []

    if cell is None:
        error_messages.append("transaction_id is None")
        return error_messages

    try:
        str(cell)
    except Exception as e:
        error_messages.append(f"In amount, exception: {e}")

    if error_messages == []:
        return
    else:
        return error_messages


def check_timestamp(cell):
    error_messages = []

    if cell is None:
        error_messages.append("Timestamp is None")
        return error_messages


    try:
        pd.to_datetime(cell)
    except Exception as e:
        error_messages.append(f"In timestamp, exception: {e}")

    if error_messages == []:
        return
    else:
        return error_messages

def check_amount(cell):
    error_messages = []

    if cell is None:
        error_messages.append(f"amount is None")
        return error_messages


    try:
        float(cell)
    except Exception as e:
        error_messages.append(f"In amount, exception: {e}")

    if error_messages == []:
        return
    else:
        return error_messages

def check_currency(cell):
    error_messages = []

    if cell is None:
        error_messages.append("currency is None")
        return error_messages


    try:
        str(cell)
    except Exception as e:
        error_messages.append(f"In currency, exception: {e}")

    if error_messages == []:
        return
    else:
        return error_messages


def check_sender_account(cell):
    error_messages = []

    if cell is None:
        error_messages.append("sender_account is None")
        return error_messages


    try:
        str(cell)
    except Exception as e:
        error_messages.append(f"In sender_account, exception: {e}")

    if error_messages == []:
        return
    else:
        return error_messages
    
def check_receiver_account(cell):
    error_messages = []

    if cell is None:
        error_messages.append("receiver_account is None")
        return error_messages


    try:
        str(cell)
    except Exception as e:
        error_messages.append(f"In receiver_account, exception: {e}")

    if error_messages == []:
        return
    else:
        return error_messages

def check_sender_country(cell):
    error_messages = []

    if cell is None:
        error_messages.append("sender_country is None")
        return error_messages


    try:
        str(cell)
    except Exception as e:
        error_messages.append(f"In sender_country, exception: {e}")

    if error_messages == []:
        return
    else:
        return error_messages

def check_sender_municipality(cell):
    error_messages = []

    if cell is None:
        error_messages.append("sender_municipality is None")
        return error_messages


    try:
        str(cell)
    except Exception as e:
        error_messages.append(f"In sender_municipality, exception: {e}")

    if error_messages == []:
        return
    else:
        return error_messages

def check_receiver_country(cell):
    error_messages = []

    if cell is None:
        error_messages.append("receiver_country is None")
        return error_messages


    try:
        str(cell)
    except Exception as e:
        error_messages.append(f"In receiver_country, exception: {e}")

    if error_messages == []:
        return
    else:
        return error_messages

def check_receiver_municipality(cell):
    error_messages = []

    if cell is None:
        error_messages.append("receiver_municipality is None")
        return error_messages


    try:
        str(cell)
    except Exception as e:
        error_messages.append(f"In receiver_municipality, exception: {e}")

    if error_messages == []:
        return
    else:
        return error_messages

def check_transaction_type(cell):
    error_messages = []

    if cell is None:
        error_messages.append("transaction_type is None")
        return error_messages

    try:
        str(cell)
    except Exception as e:
        error_messages.append(f"In transaction_type, exception: {e}")

    if error_messages == []:
        return
    else:
        return error_messages
    
def check_notes(cell):
    error_messages = []

    if cell is None:
        error_messages.append("notes is None")
        return error_messages

    try:
        str(cell)
    except Exception as e:
        error_messages.append(f"In notes, exception: {e}")

    if error_messages == []:
        return
    else:
        return error_messages

In [4]:


def first_check(dataframe):

    # starting two new dfs from dataframe
    # df_incorrect = dataframe[df_transactions.isna().any(axis=1)]
    # df_remaining = dataframe[df_transactions.notna().any(axis=1)]
    # display(df_incorrect.head())
    # display(df_remaining.head())
    for idx, row in dataframe.iterrows():
        # print(type(row))
        # print(row.index)
        for index_n, indexname in enumerate(row.index):
            print(row[indexname])
            print(row.index[index_n])
        if idx >= 0:
            return
        error_messages = []

        tr_id, time, amount, curr, s_acc, r_acc, s_country, s_mun, r_country, r_mun, t_type, notes = row

            # [check_None_dtype(tr_id, "st") if check_None_dtype(tr_id, "st") is not None else None],
            # [check_None_dtype(time, "dt") if check_None_dtype(time, "dt") is not None else None],
        if check_transaction_id(tr_id) is not None:
            error_messages.append(check_transaction_id(tr_id))
            
        if check_timestamp(time) is not None:
            error_messages.append(check_timestamp(time))
            
        if check_amount(amount) is not None:
            error_messages.append(check_amount(amount))
            
        if check_currency(curr) is not None:
            error_messages.append(check_currency(curr))
            
        if check_sender_account(s_acc) is not None:
            error_messages.append(check_sender_account(s_acc))
            
        if check_receiver_account(r_acc) is not None:
            error_messages.append(check_receiver_account(r_acc))
            
        if check_sender_country(s_country) is not None:
            error_messages.append(check_sender_country(s_country))
            
        if check_sender_municipality(s_mun) is not None:
            error_messages.append(check_sender_municipality(s_mun))
            
        if check_receiver_country(r_country) is not None:
            error_messages.append(check_receiver_country(r_country))
            
        if check_receiver_municipality(r_mun) is not None:
            error_messages.append(check_receiver_municipality(r_mun))
            
        if check_transaction_type(t_type) is not None:
            error_messages.append(check_transaction_type(t_type))
        
        if check_notes(notes) is not None:
            error_messages.append(check_notes(notes))
            
        # where there any faults discovered?
        # print(len(error_messages))
    if len(error_messages) > 0:
        print(f"error_message contains {error_messages}")
        # else:
        #     print(f"error_messages empty, however: {error_messages}")

first_check(df_transactions)

f2f3b0fc-b7d7-4d85-b682-cbf07ef77c1a
transaction_id
2025-03-06 12:04:00
timestamp
7746.03
amount
SEK
currency
SE8902EWFT80524424320740
sender_account
SE8902ZUIH32054423564254
receiver_account
Sweden
sender_country
Karlskrona
sender_municipality
Sweden
receiver_country
Eskilstuna
receiver_municipality
outgoing
transaction_type
Online purchase
notes

### ["transaction_id"] - column

In [6]:
# check for uniqueness in transaction - column
duplicates = df_transactions[df_transactions["transaction_id"].duplicated(keep=False)]
# display(duplicates) # no duplicates

In [7]:
import uuid

def is_valid_uuid(uuid_to_test, version=4):
    for key, row in uuid_to_test.iterrows():
        # print(f"{row["transaction_id"]}")
        try:
            # print(row["amount"])
            uuid_obj = uuid.UUID(row["transaction_id"], version=4)
        except Exception as e:
            print(e)
        
print(is_valid_uuid(df_transactions)) # all transaction_id are legit UUID

None

### ["amount"] - column
There are a few errors in the amount-column, such as (leading, trailing and inside) blank space

In [ ]:
# remove whitespace
# conversion from object to float not possible with blank spaces
df_transactions["amount"] = df_transactions["amount"].astype(str)
df_transactions["amount"] = df_transactions["amount"].str.replace(" ", "")
df_transactions["amount"] = df_transactions["amount"].astype(float)

print(df_transactions.dtypes) # ["amount"] is now float64
# display(df_transactions)

transaction_id            object
timestamp                 object
amount                   float64
currency                  object
sender_account            object
receiver_account          object
sender_country            object
sender_municipality       object
receiver_country          object
receiver_municipality     object
transaction_type          object
notes                     object
dtype: object

,transaction_id,timestamp,amount,currency,sender_account,receiver_account,sender_country,sender_municipality,receiver_country,receiver_municipality,transaction_type,notes
0,f2f3b0fc-b7d7-4d85-b682-cbf07ef77c1a,2025-03-06 12:04:00,7746.03,SEK,SE8902EWFT80524424320740,SE8902ZUIH32054423564254,Sweden,Karlskrona,Sweden,Eskilstuna,outgoing,Online purchase
1,feccbd1e-7752-4452-a44a-901510252561,2025-03-31 01:37:00,45193.04,SEK,SE8902GTSI58472323675409,SE8902ERNA19462716907689,Sweden,Piteå,Sweden,Norrköping,outgoing,Tax refund
2,bc6a480c-e2e1-434d-830c-1cda3f913038,2025-04-29 22:58:00,33029.71,SEK,SE8902SEZT63377163386089,SE8902LOLQ30361773270969,Sweden,Östersund,Sweden,Karlskoga,incoming,Tax refund
3,b832aa2c-77f3-4c4f-9697-9776b8d74abb,2025-02-27 14:52:00,35994.61,SEK,SE8902MGEE43594824630478,SE8902XIVG18316797897983,Sweden,Karlstad,Sweden,Helsingborg,incoming,NaN
4,0d32c6ef-508e-4f5d-bc64-341a0a9f498d,2025-01-03 22:29:00,32229.73,SEK,SE8902SZWO66860675966705,SE8902SUUS97732018069804,Sweden,Skellefteå,Sweden,Falun,outgoing,Tax refund
...,...,...,...,...,...,...,...,...,...,...,...,...
99995,ea7e0cb2-fadb-496c-962b-7e54a5cfa1bc,2025-02-03 17:00:00,146.04,USD,GB39XHRG15445191862019,SE8902AQYT55466061009593,Mauritania,Jacksonville,Sweden,Nyköping,outgoing,Gift to family member
99996,4271c3c0-d3be-49f5-8154-ee60e2a1e582,2025-01-07 14:00:00,56.98,USD,GB97OHYP64183530899251,SE8902AQYT55466061009593,Guinea,Waltersport,Sweden,Skellefteå,incoming,NaN
99997,23574238-9739-4af4-a823-5b699812db4d,2025-05-11 13:00:00,128.34,USD,GB68PWPH34390331224741,SE8902AQYT55466061009593,Tokelau,Davidfurt,Sweden,Luleå,incoming,Gift to family member
99998,38e785ff-e460-419e-af07-595f5c67aaf6,2025-02-02 13:00:00,149.13,USD,GB30NDUZ96025046626638,SE8902AQYT55466061009593,Bulgaria,West Andrewside,Sweden,Skellefteå,outgoing,Loan repayment
99999,94e5a276-d5ce-40f6-b17c-97885b455bbd,2025-05-09 15:00:00,41.77,USD,GB64JUMJ42347315082570,SE8902AQYT55466061009593,Latvia,Crawfordfort,Sweden,Varberg,outgoing,NaN

### timestamp - column

## Tool testing

In [9]:
error_columns = df_transactions.columns.tolist() + ["error_message", "saved", "do_not_run"]
display(error_columns)

['transaction_id',
 'timestamp',
 'amount',
 'currency',
 'sender_account',
 'receiver_account',
 'sender_country',
 'sender_municipality',
 'receiver_country',
 'receiver_municipality',
 'transaction_type',
 'notes',
 'error_message',
 'saved',
 'do_not_run']

In [10]:
from datetime import datetime
import random
import string

def create_unique_run_id():
    """
    Creates a unique identifier for transaction rows

    note: microseconds (%f) has 6 (six) digits
    note: if server runs are faste than 8 per milliseconds then up the length-value
    """

    # get the timestamp
    now = datetime.now().strftime("%Y%m%d%H%M%S%f")
    
    # create a random strin for absolute uniqueness
    length = 8 # accepts <8 runs per microsecond
    random_string = ''.join(random.choices(
        string.ascii_uppercase + string.digits, k=length))
    
    f = now + random_string
    return f

df_transactions["run_id"] = create_unique_run_id()
df_transactions.head()

,transaction_id,timestamp,amount,currency,sender_account,receiver_account,sender_country,sender_municipality,receiver_country,receiver_municipality,transaction_type,notes,run_id
0,f2f3b0fc-b7d7-4d85-b682-cbf07ef77c1a,2025-03-06 12:04:00,7746.03,SEK,SE8902EWFT80524424320740,SE8902ZUIH32054423564254,Sweden,Karlskrona,Sweden,Eskilstuna,outgoing,Online purchase,2025081219554185332947V4GDIV
1,feccbd1e-7752-4452-a44a-901510252561,2025-03-31 01:37:00,45193.04,SEK,SE8902GTSI58472323675409,SE8902ERNA19462716907689,Sweden,Piteå,Sweden,Norrköping,outgoing,Tax refund,2025081219554185332947V4GDIV
2,bc6a480c-e2e1-434d-830c-1cda3f913038,2025-04-29 22:58:00,33029.71,SEK,SE8902SEZT63377163386089,SE8902LOLQ30361773270969,Sweden,Östersund,Sweden,Karlskoga,incoming,Tax refund,2025081219554185332947V4GDIV
3,b832aa2c-77f3-4c4f-9697-9776b8d74abb,2025-02-27 14:52:00,35994.61,SEK,SE8902MGEE43594824630478,SE8902XIVG18316797897983,Sweden,Karlstad,Sweden,Helsingborg,incoming,NaN,2025081219554185332947V4GDIV
4,0d32c6ef-508e-4f5d-bc64-341a0a9f498d,2025-01-03 22:29:00,32229.73,SEK,SE8902SZWO66860675966705,SE8902SUUS97732018069804,Sweden,Skellefteå,Sweden,Falun,outgoing,Tax refund,2025081219554185332947V4GDIV